version: '3'

tasks:
  all:
    desc: Build all packages
    cmds:
      - task: move
      - task: packages
      - task: apps
      - echo "✅ All builds complete"

  move:
    desc: Build all Move packages
    cmds:
      - echo "🔨 Building Move packages..."
      - task: move:build

  packages:
    desc: Build TypeScript packages
    cmds:
      - echo "🔨 Building TypeScript packages..."
      - bun run --filter './packages/*' build

  apps:
    desc: Build all applications
    cmds:
      - echo "🔨 Building applications..."
      - bun run --filter './apps/*' build

  api:
    desc: Build API only
    dir: apps/api
    cmds:
      - bun run build

  web:
    desc: Build web frontend only
    dir: apps/web
    cmds:
      - bun run build
