version: '3'

tasks:
  full:
    desc: Start full development stack (Docker Compose)
    cmds:
      - echo "🚀 Starting TortoiseOS development stack..."
      - docker compose -f docker/docker-compose.yml up --build

  full-detached:
    desc: Start full stack in background
    cmds:
      - echo "🚀 Starting TortoiseOS in background..."
      - docker compose -f docker/docker-compose.yml up -d --build
      - echo "✅ Stack running in background"
      - echo "   View logs - docker compose -f docker/docker-compose.yml logs -f"
      - echo "   Stop - task dev stop"

  api:
    desc: Start API server only (requires Sui node running)
    dir: apps/api
    cmds:
      - echo "🚀 Starting TortoiseOS API..."
      - bun run dev

  web:
    desc: Start web frontend only (requires API running)
    dir: apps/web
    cmds:
      - echo "🚀 Starting TortoiseOS Web..."
      - bun run dev

  sui:
    desc: Start local Sui network only
    cmds:
      - echo "🚀 Starting Sui local network..."
      - sui-test-validator --epoch-duration-ms 60000

  stop:
    desc: Stop all development services
    cmds:
      - echo "🛑 Stopping development stack..."
      - docker compose -f docker/docker-compose.yml down
      - echo "✅ Services stopped"

  restart:
    desc: Restart development stack
    cmds:
      - task: stop
      - task: full-detached

  logs:
    desc: Follow logs from all services
    cmds:
      - docker compose -f docker/docker-compose.yml logs -f

  logs-api:
    desc: Follow API logs only
    cmds:
      - docker compose -f docker/docker-compose.yml logs -f api

  logs-web:
    desc: Follow web logs only
    cmds:
      - docker compose -f docker/docker-compose.yml logs -f web

  logs-sui:
    desc: Follow Sui node logs only
    cmds:
      - docker compose -f docker/docker-compose.yml logs -f sui-node

  status:
    desc: Check status of all services
    cmds:
      - docker compose -f docker/docker-compose.yml ps
