/**
 * Auto-generated deployed contracts
 * DO NOT EDIT MANUALLY
 * Generated by @bun-move/move-deployer
 *
 * Run `task move:deploy` to deploy contracts and regenerate this file
 */

export interface DeployedContract {
  packageId: string;
  modules: string[];
  network: string;
  deployedAt: number;
}

export const deployedContracts: Record<
  string,
  Record<string, DeployedContract>
> = {
  localnet: {
    // Will be populated after deployment
    // Example:
    // amm: {
    //   packageId: "0xabc123...",
    //   modules: ["pool"],
    //   network: "localnet",
    //   deployedAt: 1234567890
    // }
  },
  devnet: {},
  testnet: {},
  mainnet: {},
} as const;

export default deployedContracts;
