version: '3'

dotenv: ['.env', '.env.local']

includes:
  setup: ./tooling/tasks/setup.yml
  dev: ./tooling/tasks/dev.yml
  move: ./tooling/tasks/move.yml
  test: ./tooling/tasks/test.yml
  build: ./tooling/tasks/build.yml
  deploy: ./tooling/tasks/deploy.yml
  clean: ./tooling/tasks/clean.yml
  ai: ./tooling/tasks/ai.yml

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list-all
