version: '3'

dotenv: ['.env', '.env.local']

includes:
  default:
    taskfile: ./tooling/tasks/Taskfile.yml
    dir: .
    flatten: true

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list-all
